### PR TITLE
fix: clean up errors leftover from swapping out doc generation algo

### LINKED ISSUE #486: Clean up after PR #482
Remove workarounds and inconsistencies that allowed the exact same (sometimes errant) OpenAPI docs (as checked into the repo) to be generated by the update script and test suite

### PR DESCRIPTION
**Pull request by d11n**
fixes #486, closes #485

### CODE REVIEW

**Comment by d11n** [comment]
tests are failing because i did not generate ghe openapi docs

latest commit fixes bugs that correct most `responses` (especially non-object responses), most `x-code-samples`, and a small number of flags in `x-github`

i haven't touched the odd ordering of code/json-keys for `parameters` because it makes diffs impossible to read...that will be an isolated commit and maybe pr

because i was already dramatically changing `x-code-samples`, the issue with js examples being fixed by #485 is addressed in this pr too...but i did so without changing the `operationId` like in the discussion in that thread...that's because changing the `operationId` is backward-breaking and i just wanted us to pause and consider before doing it (i do realize this is a beta release, so it's okay, but it's not strictly necessary to fix the problem at hand in #485 )...however, i would still love to see `codes-of-conduct/get-conduct-code` instead of `codes_of_conduct-get-conduct-code` /cc @zeke 
https://github.com/octokit/routes/blob/d11n/486-cleanup-after-482/lib/openapi.js#L68-L79

**Comment by d11n** [comment]
if everything looks good here, i will regenerate the ghe openapi docs

and optionally, i can update `operationId` as discussed in #485 and/or clean up the parameter code (that only affects key ordering in the generated operation files, but has "untidy" code to enforce the order of the pre- #482 op files)

File: lib/endpoint/add-code-samples.js [hunk 1]
```diff
@@ -2,31 +2,43 @@ module.exports = addCodeSamples
...
+const { getScope, getIdName } = require('../openapi')
 
 // TODO: find a better place to define parameter examples
 const PARAMETER_EXAMPLES = {
   owner: 'octocat',
   repo: 'hello-world',
-  issue_number: 1,
-  title: 'title'
+  email: 'info@github.com',
+  emails: [ 'info@github.com' ]
```
Comment (gr2m) [inline lib/endpoint/add-code-samples.js]: `octocat@github.com`

File: lib/endpoint/add-code-samples.js [hunk 2]
```diff
@@ -38,232 +50,74 @@ function toShellExample ({ route, scope, baseUrl }) {
...
+    case 'object':
+      return mapValues(
+        schema.properties,
+        (propSchema, propName) => getExampleParamValue(propName, propSchema)
+      )
+    case 'array':
+      return [ getExampleParamValue(name, schema.items) ]
   }
-  return {}
+  return '???' // unknown data type
```
Comment (gr2m) [inline lib/endpoint/add-code-samples.js]: should we throw an error so the unknown data type is added instead of setting example value to `???`

Comment (d11n) [reply lib/endpoint/add-code-samples.js]: i thought about that...but because this is the result of scraping, throwing seemed a bit heavy-handed...it currently never gets there for `api.github.com`...i'm not necessarily opposed to throwing tho

File: lib/endpoint/add-code-samples.js (hunk 1 above)
Comment (d11n) [reply lib/endpoint/add-code-samples.js]: updated it

File: lib/endpoint/add-code-samples.js (hunk 2 above)
Comment (gr2m) [reply lib/endpoint/add-code-samples.js]: If it never gets there, let's throw. Because if we get there in future it will be most likely some kind of inconsistency with additions to the docs and we would catch it that way explicitly
