### PR TITLE
Fix: Repos: Update branch protection: `dismissal_restrictions.*` should be `required_pull_request_reviews .dismissal_restrictions.*`

### LINKED ISSUE #97: Repos: Update branch protection: `dismissal_restrictions.*` should be `required_pull_request_reviews .dismissal_restrictions.*`
- endpoint scope: Repos
- endpoint name: Update branch protection
- route: `PUT /repos/:owner/:repo/branches/:branch/protection`
- documentation URL: https://developer.github.com/v3/repos/branches/#update-branch-protection

### Current specification

https://github.com/octokit/routes/blob/a509e1a89672025ec580405648b9c5666e3e7b06/routes/repos/branches/update-branch-protection.json#L25-L36

### I expected

<details>
  <summary><code>dismissal_restrictions.teams</code> should be <code>required_pull_request_reviews .dismissal_restrictions.teams</code>, <code>dismissal_restrictions.users</code> should be <code>required_pull_request_reviews .dismissal_restrictions.users</summary>

```json
{
  "name": "Update branch protection",
  "enabledForApps": true,
  "method": "PUT",
  "path": "/repos/:owner/:repo/branches/:branch/protection",
  "params": [
    {
      "name": "owner",
      "type": "string",
      "required": true,
      "description": ""
    },
    {
      "name": "repo",
      "type": "string",
      "required": true,
      "description": ""
    },
    {
      "name": "branch",
      "type": "string",
      "required": true,
      "description": ""
    },
    {
      "name": "required_status_checks",
      "type": "object",
      "description": "Require status checks to pass before merging. Set to `null` to disable.",
      "required": true,
      "allowNull": true
    },
    {
      "name": "required_status_checks.strict",
      "type": "boolean",
      "description": "Require branches to be up to date before merging.",
      "required": true
    },
    {
      "name": "required_status_checks.contexts",
      "type": "array",
      "description": "The list of status checks to require in order to merge into this branch",
      "required": true
    },
    {
      "name": "enforce_admins",
      "type": "boolean",
      "description": "Enforce all configured restrictions for administrators. Set to `true` to enforce required status checks for repository administrators. Set to `null` to disable.",
      "required": true,
      "allowNull": true
    },
    {
      "name": "required_pull_request_reviews",
      "type": "object",
      "description": "Require at least one approving review on a pull request, before merging. Set to `null` to disable.",
      "required": true,
      "allowNull": true
    },
    {
      "name": "required_pull_request_reviews.dismissal_restrictions",
      "type": "object",
      "description": "Specify which users and teams can dismiss pull request reviews. Pass an empty `dismissal_restrictions` object to disable. User and team `dismissal_restrictions` are only available for organization-owned repositories. Omit this parameter for personal repositories.",
      "required": false
    },
    {
      "name": "required_pull_request_reviews.dismissal_restrictions.users",
      "type": "array",
      "description": "The list of user `login`s with dismissal access",
      "required": false
    },
    {
      "name": "required_pull_request_reviews.dismissal_restrictions.teams",
      "type": "array",
      "description": "The list of team `slug`s with dismissal access",
      "required": false
    },
    {
      "name": "required_pull_request_reviews.dismiss_stale_reviews",
      "type": "boolean",
      "description": "Set to `true` if you want to automatically dismiss approving reviews when someone pushes a new commit.",
      "required": false
    },
    {
      "name": "required_pull_request_reviews.require_code_owner_reviews",
      "type": "boolean",
      "description": "Blocks merging pull requests until code owners review them.",
      "required": false
    },
    {
      "name": "required_pull_request_reviews.required_approving_review_count",
      "type": "integer",
      "description": "Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6.",
      "required": false
    },
    {
      "name": "restrictions",
      "type": "object",
      "description": "Restrict who can push to this branch. Team and user `restrictions` are only available for organization-owned repositories. Set to `null` to disable.",
      "required": true,
      "allowNull": true
    },
    {
      "name": "restrictions.users",
      "type": "array",
      "description": "The list of user `login`s with push access",
      "required": false
    },
    {
      "name": "restrictions.teams",
      "type": "array",
      "description": "The list of team `slug`s with push access",
      "required": false
    }
  ],
  "description": "Protecting a branch requires admin or owner permissions to the repository.\n\n**Note**: Passing new arrays of `users` and `teams` replaces their previous values.\n\n**Note**: The list of users and teams in total is limited to 100 items.",
  "documentationUrl": "https://developer.github.com/v3/repos/branches/#update-branch-protection"
}
```
</details>

---

If you’d like to work on it, just comment below and follow instructions in [CONTRIBUTING.md](https://github.com/octokit/routes/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by aryannarora**
fixes #97

### CODE REVIEW

File: lib/endpoint/tags/table.js [hunk 1]
```diff
@@ -130,6 +130,10 @@ function rowToParameter (i, el) {
     params.type = 'integer[]'
   }
 
+  if (/^dismissal_restrictions/.test(params.name)) {
```
Comment (aryannarora) [inline lib/endpoint/tags/table.js]: @knrt10 For some reason, it's not getting into this condition. Any idea why?

Comment (knrt10) [reply lib/endpoint/tags/table.js]: @aryannarora you need to do this ```params.name = `${params.name}` ```

Comment (knrt10) [reply lib/endpoint/tags/table.js]: @aryannarora the problem you are facing because you have to fetch latest master first and rebase it. As some code has been changed there. Then You need to change
 ``` if (/^dismissal_restrictions/.test(params.name)) {```
code according to that.

Comment (aps120797) [reply lib/endpoint/tags/table.js]: Yeah, it appears Travis test is failing as your branch is far behind master of `octokit/routes`, try syncing your master branch with master of `octokit/routes`. When your get your master updated, fix the code again and update your PR.

Comment (aryannarora) [reply lib/endpoint/tags/table.js]: @knrt10 I guess that is not the issue here. I'm not using any code that's modified in recent commits. Still letme first resolve all the conflicts.

Comment (aryannarora) [reply lib/endpoint/tags/table.js]: @gr2m @knrt10 
I logged out all the `params.name` in a file and turns out it doesn't contains any `dismissal_restrictions.*` . Am i missing something?
Would look into it more after some sleep.

**Comment by gr2m** [comment]
hey you two, I’ll be back next week from vacation and can look into it then. What are your current blockers/questions?

**Comment by aryannarora** [comment]
@gr2m enjoy the vacations. :)
I'll look more today and then update here. Been busy from quite a few days.

**Comment by aryannarora** [comment]
@gr2m Parameters' name are generated in **table.js** but could you point to the location where these names are actually combined? Like i got `dismissal_restrictions` and `users` as two parameter names by using `params.name` in **table.js** but not the combined one, i.e, `dismissal_restrictions.users`.

**Comment by gr2m** [comment]
The idea is that the code in [lib/endpoint/tags](https://github.com/octokit/routes/tree/master/lib/endpoint/tags) just parses the HTML reads out the information as is, without much processing, or as little as possible.

The combined parameters such as `dismissal_restrictions.users` are not in the same `<table>` tag, so the logic in `lib/endpoint/tags/table.js` cannot find it. 

Instead we go trough all the blocks in `lib/endpoint/find-parameters.js` to find parameters across multiple html tags. The logic you are looking for is here:
https://github.com/octokit/routes/blob/60c9c25c9097186f135e4f564cb6b20103099881/lib/endpoint/find-parameters.js#L179-L198

Does that answer your question?

**Comment by gr2m** [comment]
I’ll need to finish this up tomorrow as it is close to the last remaining blocker of https://github.com/octokit/rest.js/pull/822. I’ll probably look into it around 8am LA time tomorrow (Wednesday), if you could figure it out by then that'd be really 🆒😎

**Comment by aryannarora** [comment]
Done. :)

File: index.json [hunk 2]
```diff
@@ -11269,14 +11269,14 @@
...
-          "name": "dismissal_restrictions.users",
+          "name": "required_pull_request_reviews.dismissal_restrictions.users",
           "type": "string[]",
           "description": "The list of user `login`s with dismissal access",
           "required": false,
           "location": "body"
         },
         {
-          "name": "dismissal_restrictions.teams",
+          "name": "required_pull_request_reviews.dismissal_restrictions.teams",
```
Comment (gr2m) [inline index.json]: my fault, but this is a regression, `dismissal_restrictions.*` is correct in this place, see
https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch

I’ll fix that

**Comment by aryannarora** [comment]
@gr2m Thankyou. ;)

File: index.json (hunk 2 above)
Comment (aryannarora) [reply index.json]: Didn't get it. :confused:
