### PR TITLE
Multiple Issue Fix.

### LINKED ISSUE #94: Teams - Create a team: "privacy" is an enum
- endpoint scope: Teams
- endpoint name: Create a team
- route: `POST /orgs/:org/teams`
- documentation URL: https://developer.github.com/v3/teams/#create-team

### Current specification

https://github.com/octokit/routes/blob/a509e1a89672025ec580405648b9c5666e3e7b06/routes/teams/create-team.json#L37-L43

### I expected

<details>
  <summary>"privacy" parameter should have "enum" options</summary>

```json
{
  "name": "Create team",
  "enabledForApps": false,
  "method": "POST",
  "path": "/orgs/:org/teams",
  "params": [
    {
      "name": "org",
      "type": "string",
      "required": true,
      "description": ""
    },
    {
      "name": "name",
      "type": "string",
      "description": "The name of the team.",
      "required": true
    },
    {
      "name": "description",
      "type": "string",
      "description": "The description of the team.",
      "required": false
    },
    {
      "name": "maintainers",
      "type": "array of strings",
      "description": "The logins of organization members to add as maintainers of the team.",
      "required": false
    },
    {
      "name": "repo_names",
      "type": "array of strings",
      "description": "The full name (e.g., \"organization-name/repository-name\") of repositories to add the team to.",
      "required": false
    },
    {
      "name": "privacy",
      "type": "string",
      "description": "The level of privacy this team should have. The options are:  \n**For a non-nested team:**  \n\\* `secret` \\- only visible to organization owners and members of this team.  \n\\* `closed` \\- visible to all members of this organization.  \nDefault: `secret`  \n**For a parent or child team:**  \n\\* `closed` \\- visible to all members of this organization.  \nDefault for child team: `closed`  \n**Note**: You must pass the `hellcat-preview` media type to set privacy default to `closed` for child teams. **For a parent or child team:**  ",
      "default": "secret",
      "required": false,
      "enum": [
        "secret",
        "closed"
      ]
    },
    {
      "name": "permission",
      "type": "string",
      "description": "**Deprecated**. The permission that new repositories will be added to the team with when none is specified. Can be one of:  \n\\* `pull` \\- team members can pull, but not push to or administer newly-added repositories.  \n\\* `push` \\- team members can pull and push, but not administer newly-added repositories.  \n\\* `admin` \\- team members can pull, push and administer newly-added repositories.",
      "default": "pull",
      "required": false,
      "enum": [
        "pull",
        "push",
        "admin"
      ]
    },
    {
      "name": "parent_team_id",
      "type": "integer",
      "description": "The ID of a team to set as the parent team. **Note**: You must pass the `hellcat-preview` media type to use this parameter.",
      "required": false
    }
  ],
  "description": "To create a team, the authenticated user must be a member of `:org`.",
  "documentationUrl": "https://developer.github.com/v3/teams/#create-team"
}
```
</details>

---

If you’d like to work on it, just comment below and follow instructions in [CONTRIBUTING.md](https://github.com/octokit/routes/blob/master/CONTRIBUTING.md)

### LINKED ISSUE #96: Reactions: "content" parameter is an enum
- endpoint scope: Reactions
- endpoint name: Pretty much all of them, but for example "List reactions for an issue" and "Create reaction for an issue"
- documentation URL: https://developer.github.com/v3/reactions

### Current specifications

https://github.com/octokit/routes/blob/a509e1a89672025ec580405648b9c5666e3e7b06/routes/reactions/list-reactions-for-an-issue.json#L25-L30

https://github.com/octokit/routes/blob/a509e1a89672025ec580405648b9c5666e3e7b06/routes/reactions/create-reaction-for-an-issue.json#L25-L30

### I expected

The `"content"` parameter should be an an enum with the options 

```json
[
  "+1",
  "-1",
  "laugh",
  "confused",
  "heart",
  "hooray"
]
```

If you’d like to work on it, just comment below and follow instructions in [CONTRIBUTING.md](https://github.com/octokit/routes/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by knrt10**
closes #94, #95, #96, #98 and #99  .

### CODE REVIEW

**Comment by knrt10** [comment]
@gr2m Please review.

File: lib/endpoint/tags/table.js [hunk 1]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
     params.type = 'objects[]'
   }
 
+  if (params.name === 'content') {
+    if (/reaction type/.test(params.description) === true) {
+      params.enum = ['+1',
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: can you move the `'+1'` to the next line?

File: lib/endpoint/tags/table.js [hunk 2]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+        'laugh',
+        'confused',
+        'heart',
+        'hooray']
+    }
+  }
+
+  if (params.name === 'type') {
+    if (/Normally this is a `commit`/.test(params.description) === true) {
+      params.enum = ['commit',
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: can you move the `'commit'` to the next line?

File: lib/endpoint/tags/table.js [hunk 3]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+        'tree',
+        'blob']
+    }
+  }
+
+  if (params.name === 'state') {
+    if (/active/.test(params.description) === true) {
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: I think just checking for `/active/` is too risky, it could easily cause false positive in future. I’d suggest we check for `/only `"active"` will be accepted/i`

File: lib/endpoint/tags/table.js [hunk 4]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+      params.enum = ['active']
+    }
+  }
+
+  if (params.name === 'default_repository_permission') {
+    if (/organization repositories:/.test(params.description) === true) {
+      params.enum = ['read',
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: can you move the `'read'` to the next line?

File: lib/endpoint/tags/table.js [hunk 5]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+  }
+
+  if (params.name === 'state') {
+    if (/active/.test(params.description) === true) {
+      params.enum = ['active']
+    }
+  }
+
+  if (params.name === 'default_repository_permission') {
+    if (/organization repositories:/.test(params.description) === true) {
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: I feel like for this one we should try to match the pattern which looks to me like

```
\n* `<parameter>` - <description>
```

File: lib/endpoint/tags/table.js [hunk 6]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+        '-1',
+        'laugh',
+        'confused',
+        'heart',
+        'hooray']
+    }
+  }
+
+  if (params.name === 'type') {
+    if (/Normally this is a `commit`/.test(params.description) === true) {
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: I think this is such a special case, we can as well check for the entire sentence:

```
/Normally this is a `commit` but it can also be a `tree` or a `blob/
```

File: lib/endpoint/tags/table.js [hunk 7]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+      params.enum = ['read',
+        'write',
+        'admin',
+        'none']
+    }
+  }
+
+  if (params.name === 'privacy') {
+    if (params.default === 'secret') {
+      params.enum = ['secret',
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: can you move the `'secret'` to the next line?

File: lib/endpoint/tags/table.js [hunk 8]
```diff
@@ -126,6 +126,47 @@ function rowToParameter (i, el) {
...
+    if (/organization repositories:/.test(params.description) === true) {
+      params.enum = ['read',
+        'write',
+        'admin',
+        'none']
+    }
+  }
+
+  if (params.name === 'privacy') {
+    if (params.default === 'secret') {
```
Comment (gr2m) [inline lib/endpoint/tags/table.js]: I think here the conditions are simple enough to combine them into

```
params.name === 'privacy' || params.default === 'secret'
```

Comment (knrt10) [reply lib/endpoint/tags/table.js]: I think it should be `params.name === 'privacy' && params.default === 'secret'`

File: lib/endpoint/tags/table.js (hunk 5 above)
Comment (knrt10) [reply lib/endpoint/tags/table.js]: I think for this `Default permission level members have for organization repositories:` would work. Is it ok?

File: lib/endpoint/tags/table.js (hunk 8 above)
Comment (gr2m) [reply lib/endpoint/tags/table.js]: yes, you are right :)

Comment (knrt10) [reply lib/endpoint/tags/table.js]: let me update the branch.

File: lib/endpoint/tags/table.js (hunk 5 above)
Comment (gr2m) [reply lib/endpoint/tags/table.js]: okay, good enough for now :). I wonder if we have this pattern in other places

```
\n* `<parameter>` - <description>
```

If we do, we should remove this workaround and implement more flexible pattern matching.

**Comment by knrt10** [comment]
@gr2m  updated the branch.
